http:
  listener:
    host: "0.0.0.0"
    port: "9082"
    path: "/fastGoCall/{serviceType}"
    
db:
  mySQL:
    host: "sql12.freesqldatabase.com"
    port: "3306"
    username: "sql12599830"
    password: "n52bkXy7EL"
    database: "sql12599830"
    